# Generated by Django 3.0.6 on 2020-05-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20200509_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KirrURLManager',
        ),
    ]
